import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from ncbi_genome_download import NgdConfig
from ncbi_genome_download.core import (
    create_downloadjob,
    select_candidates,
    worker,
)

from genomesieve.services.ncbi_search import GenomeRecord


class GenomeDownloadError(Exception):
    """Raised when genome files cannot be downloaded."""


@dataclass
class DownloadProgress:
    completed_files: int
    total_files: int
    percentage: int
    eta_seconds: float | None
    last_completed_file: str | None


@dataclass
class GenomeDownloadResult:
    destination: Path
    requested_assemblies: int
    requested_formats: list[str]
    completed_files: int


def download_genomes(
    records: list[GenomeRecord],
    file_formats: list[str],
    destination: str,
    progress_callback: Callable[[DownloadProgress], None] | None = None,
    status_callback: Callable[[str], None] | None = None,
) -> GenomeDownloadResult:
    """
    Download exactly the assemblies selected by GenomeSieve.

    Progress is calculated from the actual download jobs generated by
    ncbi-genome-download. Each job corresponds to one file that needs
    to be downloaded and checksum-verified.
    """

    if not records:
        raise GenomeDownloadError(
            "There are no selected assemblies to download."
        )

    if not file_formats:
        raise GenomeDownloadError(
            "Select at least one file format."
        )

    destination_path = Path(destination)

    try:
        destination_path.mkdir(
            parents=True,
            exist_ok=True,
        )

    except OSError as exc:
        raise GenomeDownloadError(
            f"Could not create the destination folder: {exc}"
        ) from exc

    accessions = [
        record.accession
        for record in records
    ]

    if status_callback:
        status_callback(
            "Preparing download and checking available files..."
        )

    # ncbi-genome-download configuration.
    #
    # We use exact RefSeq accessions selected during the search.
    # GenomeSieve manages parallelism itself so it can track each
    # completed file.
    try:
        config = NgdConfig.from_kwargs(
            groups=["bacteria"],
            section="refseq",
            file_formats=file_formats,
            assembly_accessions=accessions,
            output=str(destination_path),
            flat_output=True,
            parallel=1,
            use_cache=True,
        )

        candidates = select_candidates(config)

    except Exception as exc:
        raise GenomeDownloadError(
            f"Could not prepare genome downloads: {exc}"
        ) from exc

    if not candidates:
        raise GenomeDownloadError(
            "No matching RefSeq assemblies were found for download."
        )

    # ============================================================
    # CREATE DOWNLOAD JOBS
    # ============================================================

    download_jobs = []

    for entry, group in candidates:
        try:
            jobs = create_downloadjob(
                entry,
                group,
                config,
            )

            download_jobs.extend(jobs)

        except Exception as exc:
            raise GenomeDownloadError(
                "Could not prepare files for "
                f"{entry.get('assembly_accession', 'unknown')}: {exc}"
            ) from exc

    total_files = len(download_jobs)

    # If no jobs were generated, the requested files are already
    # present and valid in the destination folder.
    if total_files == 0:
        if progress_callback:
            progress_callback(
                DownloadProgress(
                    completed_files=0,
                    total_files=0,
                    percentage=100,
                    eta_seconds=0,
                    last_completed_file=None,
                )
            )

        return GenomeDownloadResult(
            destination=destination_path,
            requested_assemblies=len(records),
            requested_formats=file_formats,
            completed_files=0,
        )

    if status_callback:
        status_callback(
            f"Downloading {total_files} file"
            f"{'s' if total_files != 1 else ''}..."
        )

    # Initial progress state.
    if progress_callback:
        progress_callback(
            DownloadProgress(
                completed_files=0,
                total_files=total_files,
                percentage=0,
                eta_seconds=None,
                last_completed_file=None,
            )
        )

    # ============================================================
    # DOWNLOAD
    # ============================================================

    start_time = time.monotonic()
    completed_files = 0

    # Four concurrent downloads is a conservative default and matches
    # the parallelism used in the previous implementation.
    max_workers = min(4, total_files)

    try:
        with ThreadPoolExecutor(
            max_workers=max_workers
        ) as executor:

            future_to_job = {
                executor.submit(worker, job): job
                for job in download_jobs
            }

            for future in as_completed(future_to_job):
                job = future_to_job[future]

                result = future.result()

                if result is False:
                    raise GenomeDownloadError(
                        "A downloaded file failed checksum validation: "
                        f"{Path(job.local_file).name}"
                    )

                completed_files += 1

                elapsed = time.monotonic() - start_time

                percentage = round(
                    completed_files
                    / total_files
                    * 100
                )

                # Estimate remaining time using observed throughput.
                if completed_files > 0:
                    average_time = (
                        elapsed / completed_files
                    )

                    remaining_files = (
                        total_files - completed_files
                    )

                    eta_seconds = (
                        average_time * remaining_files
                    )

                else:
                    eta_seconds = None

                if progress_callback:
                    progress_callback(
                        DownloadProgress(
                            completed_files=completed_files,
                            total_files=total_files,
                            percentage=percentage,
                            eta_seconds=eta_seconds,
                            last_completed_file=Path(
                                job.local_file
                            ).name,
                        )
                    )

    except GenomeDownloadError:
        raise

    except Exception as exc:
        raise GenomeDownloadError(
            f"Genome download failed: {exc}"
        ) from exc

    return GenomeDownloadResult(
        destination=destination_path,
        requested_assemblies=len(records),
        requested_formats=file_formats,
        completed_files=completed_files,
    )